---
- name: Install nginx packages.
  package:
    name: nginx-mainline
    state: present

- name: ensure vhost conf dir
  file:
    path: /etc/nginx/vhosts.d
    state: directory

- name: ensure nginx configuration file.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: start and enable nginx service.
  systemd:
    name: nginx
    state: started
    enabled: true
  notify:
    - restart nginx
