---
- name: Re-create a iobroker container
  docker_container:
    name: iobroker
    image: buanet/iobroker
    state: started
    network_mode: host
    groups: uucp
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - iobrokerdata:/opt/iobroker
