---
- name: Re-create a iobroker container
  docker_container:
    name: iobroker
    image: buanet/iobroker
    state: present
    recreate: yes
    exposed_ports:
      - 6379
    volumes:
      - /iobroker
