---
- include_vars: "{{ ansible_distribution }}.yml"
- include_tasks: "{{ ansible_distribution }}.yml"

- name: ensure nodejs is installed
  package:
    name:
      - "{{ nodejs_package }}"
#      - yarn
#      - npm
    state: present

- name: ensure typescript is installed
  npm:
    name: typescript
    state: present
    global: true
