---
- name: ensure nodejs is installed
  package:
    name:
      - nodejs-lts-gallium
      - yarn
      - npm
    state: present

- name: ensure typescript is installed
  npm:
    name: typescript
    state: present
    global: true
