---
- name: ensure alarm user is absent.
  user:
    name: alarm
    state: absent

- name: ensure cronie is installed.
  package:
    name: cronie
    state: present

- name: ensure keymap and font set.
  lineinfile:
    create: true
    path: /etc/vconsole.conf
    regexp: "^{{ item.key }}"
    value: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: 'KEYMAP', value: 'de-latin1' }
    - { key: 'FONT', value: 'lat9w-16' }

- name: gather package facts
  package_facts:
    manager: auto

- name: ensure yay is cloned.
  become: false
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: /tmp/yay
  when: "'yay' not in ansible_facts.packages"

- name: ensure yay is installed.
  become: false
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  when: "'yay' not in ansible_facts.packages"

- name: ensure yay sources are absent.
  file:
    path: /tmp/yay
    state: absent
  when: "'yay' not in ansible_facts.packages"
