---
- name: create hue2mqtt user
  user:
    name: "{{ hue2mqtt_user }}"

- name: ensure python setup-tools are installed
  package:
    name:
      - python-setuptools
      - python-pip
    state: present

- name: ensure hue2mqtt is installed
  pip:
    name: hue2mqtt
    state: present

- name: ensure hue2mqtt configuration exists
  template:
    src: hue2mqtt.toml.j2
    dest: /etc/hue2mqtt.toml

- name: ensure systemd hue2mqtt service exists
  template:
    src: hue2mqtt.service.j2
    dest: /usr/lib/systemd/system/hue2mqtt.service
  notify:
    - restart hue2mqtt

- name: daemon reload for hue2mqtt.service
  systemd:
    daemon_reload: yes
  notify:
    - restart hue2mqtt
