---
- name: ensure mosquitto exists
  package:
    name: mosquitto
    state: present

- name: start and enable mosquitto service.
  systemd:
    name: mosquitto
    enabled: true
  notify:
    - restart mosquitto

- name: ensure configuration exists as expected
  lineinfile:
      dest: "/etc/mosquitto/mosquitto.conf"
      line: '{{ item.key }} {{ item.value }}'
      regexp: "^{{ item.key }}.*$"
    with_dict: "{{ mosquitto_conf }}"
