---
- name: ensure prerequisite packages are present
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: ensure sury apt key exists
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

- name: ensure sury apt repository exists
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present

- name: update repository cache
  apt:
    update_cache: true
