---
- name: ensure docker is installed
  package:
    name: docker
    state: present

- name: ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: true
  notify:
    - restart docker

- name: ensure docker data directory exists
  file:
    path: "{{ docker_data_root_directory }}"
    state: directory

- name: ensure docker deamon.json exists
  template:
    src: deamon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: ensure python-docker exists
  package:
    name: python-docker
    state: present
