---
- include_tasks: "{{ ansible_distribution }}.yml"

- name: ensure php packages are installed.
  package:
    name: '{{ php_packages }}'
    state: present
  notify:
    - restart php-fpm

- name: ensure php directories exist
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
    owner: "{{ fpm_user }}"
    group: "{{ fpm_group }}"
    recurse: true
  loop:
    - "{{ fpm_log_path }}"
    - "{{ fpm_session_path }}"

#
#- name: ensure composer exists
#  package:
#    name: composer
#    state: present
#
#- name: ensure composer cache is readable
#  file:
#    path: "/srv/http/.cache/composer"
#    recurse: true
#    owner: "{{ fpm_user }}"
