---
- name: ensure php packages are installed.
  package:
    name:
     - php
     - php-fpm
     - php-intl
     - php-gd
     - php-apcu
    state: present
  notify:
    - restart php-fpm

- name: ensure php.ini settings.
  lineinfile:
    dest: '/etc/php/php.ini'
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: "^{{ item.key }}.*$"
  with_dict: "{{ php_ini }}"
  notify:
    - restart php-fpm

- name: ensure php log dir exists
  file:
    path: "{{ fpm_log_path }}"
    state: directory
    owner: "{{ fpm_user }}"
    group: "{{ fpm_group }}"
    recurse: true

- name: place php-fpm configuration file.
  template:
    src: fpm-www.conf.j2
    dest: /etc/php/php-fpm.d/www.conf
  notify:
    - restart php-fpm

- name: start and enable php-fpm service.
  systemd:
    name: php-fpm
    enabled: true
