---
- name: ensure php packages are installed.
  package:
    name:
     - php
     - php-fpm
     - php-intl
     - php-gd
     - php-apcu
     - php-sqlite
     - sqlite
    state: present
  notify:
    - restart php-fpm

- name: ensure php.ini settings.
  lineinfile:
    dest: "/etc/php/php.ini"
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: "^{{ item.key }}.*$"
  with_dict: "{{ php_ini }}"
  notify:
    - restart php-fpm

- name: ensure php extensions present
  copy:
    content: "extension={{ item }}\n"
    dest: "/etc/php/conf.d/{{ item }}.ini"
  loop: "{{ php_extensions }}"
  notify:
    - restart php-fpm

- name: ensure php directories exist
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
    owner: "{{ fpm_user }}"
    group: "{{ fpm_group }}"
    recurse: true
  loop:
    - "{{ fpm_log_path }}"
    - "{{ fpm_session_path }}"

- name: place php-fpm configuration file.
  template:
    src: fpm-www.conf.j2
    dest: /etc/php/php-fpm.d/www.conf
  notify:
    - restart php-fpm

- name: start and enable php-fpm service.
  systemd:
    name: php-fpm
    enabled: true

- name: ensure composer exists
  package:
    name: composer
    state: present

- name: ensure composer cache is readable
  file:
    path: "/srv/http/.cache/composer"
    recurse: true
    owner: "{{ fpm_user }}"
