---
- name: ensure prerequisite packages are present
  package:
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - bluez
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - autoconf
      - build-essential
      - libopenjp2-7
      - libtiff5
      - libturbojpeg0-dev
      - tzdata
    state: present

- name: create homeassistant user
  user:
    name: "{{ homeassistant_user }}"

- name: ensure homeassistant is installed
  pip:
    name: homeassistant
    state: present

- name: ensure systemd homeassistant service exists
  template:
    src: homeassistant.service.j2
    dest: /usr/lib/systemd/system/homeassistant.service
  notify:
    - restart homeassistant

- name: daemon reload for homeassistant.service
  systemd:
    daemon_reload: yes
  notify:
    - restart homeassistant

- name: start and enable homeassistant service.
  systemd:
    name: homeassistant
    enabled: true
  notify:
    - restart homeassistant
