---
- hosts: home
  pre_tasks:
    - name: Wait 300 seconds, but only start checking after 5 seconds
      wait_for_connection:
        delay: 5
        timeout: 300
    - name: world can write to remote_tmp
      file:
        path: /tmp/.ansible
        state: directory
        mode: 0777
        recurse: true
  tasks:
    - name: ensure system is installed
      include_role:
        name: system
        vars_from: "{{ ansible_distribution }}"
        apply:
          become: true
    - name: ensure zsh is installed
      include_role:
        name: zsh
        apply:
          become: true
    - name: ensure docker is installed
      include_role:
        name: docker
        apply:
          become: true
    - name: ensure pihole is installed
      include_role:
        name: pihole
        apply:
          become: true
    - name: ensure zigbee2mqtt is installed
      include_role:
        name: zigbee2mqtt
        apply:
          become: true
    - name: ensure iobroker is installed
      include_role:
        name: iobroker
        apply:
          become: true
    - name: ensure fastlane is installed
      include_role:
        name: fastlane
        apply:
          become: true
