---
- hosts: home
  pre_tasks:
    - name: Wait 300 seconds, but only start checking after 5 seconds
      wait_for_connection:
        delay: 5
        timeout: 300
  tasks:
    - name: update cache
      package:
        update_cache: yes
      become: true
    - name: upgrade
      package:
        upgrade: yes
      become: true
    - name: update iobroker
      command: "iob {{ item }}"
      loop:
        - backup
        - stop
        - update
        - fix
        - upgrade self
        - start
