---
- name: check pihole for existence
  stat:
    path: /srv/http/pihole
  register: pihole

- name: ensure pihole is installed
  become_user: yay
  command: yay -S pi-hole-server --noconfirm
  when: pihole.stat.isdir is defined and not pihole.stat.isdir

- name: ensure read and write permissions are granted
  lineinfile:
    path: /etc/pihole/pihole-FTL.conf
    regexp: '^{{ item.key }}'
    value: '{{ item.key }}={{ item.value }}'
  loop:
    - { key: 'DBINTERVAL', value: '60.0' }
    - { key: 'PRIVACYLEVEL', value: '3' }

- name: ensure pihole vhost file for nginx exists
  template:
    src: pihole-nginx.conf.j2
    dest: /etc/nginx/vhosts.d/pihole.conf

- name: ensure directory for systemd service exists
  file:
    path: /usr/lib/systemd/system/php-fpm.service.d
    state: directory

- name: reload systemd config
  systemd:
    daemon_reload: yes

- name: create drop-in-file for php-fpm
  copy:
    src: pihole.conf
    dest: /usr/lib/systemd/system/php-fpm.service.d/pihole.conf
  notify:
    - restart php-fpm

- name: update adlists
  copy:
    src: adlists.list
    dest: /etc/pihole/adlists.list
